### ISSUE TITLE
Security vulnerability in tc-core-library-js

### ISSUE THREAD

**Issue by sharathkumaranbu** [appirio-tech/tc-core-library-js#17]
`npm audit` command in tc-core-library-js reports

```
found 4 vulnerabilities (2 moderate, 2 high)
```

These vulnerabilities are propagated to every Topcoder API which uses `tc-core-library-js` for JWT Authentication and M2M token handling.

I believe it makes sense to fix these security vulnerabilities.

cc @cwdcwd @sachin-maheshwari

**Comment by sachin-maheshwari** [comment]
Thanks! @sharathkumaranbu. We'll address this issue in PR -https://github.com/appirio-tech/tc-core-library-js/pull/18 and share new tag shortly after testing.

**Comment by cwdcwd** [comment]
looks like #18 was merged. closing
